---
- name: Добавить helm-репозиторий argo-cd
  kubernetes.core.helm_repository:
    name: argo
    repo_url: https://argoproj.github.io/argo-helm
  delegate_to: localhost
  become: false
  run_once: true

- name: Установить argo-cd
  kubernetes.core.helm:
    name: argocd
    chart_ref: argo/argo-cd
    chart_version: "{{ argo_cd_version }}"
    create_namespace: true
    release_namespace: argocd
    kubeconfig: "{{ kubeconfig_path }}"
    wait: true
    wait_timeout: 10m
    values:
        configs:
          params:
            server.insecure: true
  delegate_to: localhost
  become: false
  run_once: true

- name: Ingress для argo-cd
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig_path }}"
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: argocd-server
        namespace: argocd
        annotations:
          cert-manager.io/cluster-issuer: lab-ca-issuer
      spec:
        ingressClassName: nginx
        tls:
          - hosts:
              - argocd.lab.local
            secretName: argocd-server-tls
        rules:
          - host: argocd.lab.local
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: argocd-server
                      port:
                        number: 80
  delegate_to: localhost
  become: false
  run_once: true

