- name: Добавить helm-репозиторий ingress-nginx
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx
  delegate_to: localhost
  become: false
  run_once: true

- name: Установить ingress-nginx
  kubernetes.core.helm:
    name: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    chart_version: "{{ ingress_nginx_version }}"
    create_namespace: true
    release_namespace: ingress-nginx
    kubeconfig: "{{ kubeconfig_path }}"
    wait: true
    wait_timeout: 10m
    values:
      controller:
        service:
          type: LoadBalancer
        ingressClassResource:
          default: true
  delegate_to: localhost
  become: false
  run_once: true