---
- import_playbook: playbooks/10-common.yml
- import_playbook: playbooks/20-containerd.yml
- import_playbook: playbooks/25-kube-tools.yml
- import_playbook: playbooks/30-control-plane.yml
- import_playbook: playbooks/40-workers.yml
- import_playbook: playbooks/50-cni.yml
- import_playbook: playbooks/60-platform.yml